import { z } from "zod";
const id = z.string().trim().min(1).max(64);
const optionalText = (max: number) => z.preprocess((value) => value == null || (typeof value === "string" && value.trim() === "") ? undefined : value, z.string().trim().max(max).optional());
const optionalHttpsUrl = z.preprocess((value) => value == null || (typeof value === "string" && value.trim() === "") ? undefined : value, z.string().trim().url("Enter a complete URL.").refine((value) => { try { return new URL(value).protocol === "https:"; } catch { return true; } }, "Use a secure HTTPS URL.").optional());
const order = z.preprocess((value) => typeof value === "string" && value.trim() !== "" ? Number(value) : value, z.number().int().min(0, "Order cannot be negative.").max(1_000_000));
export const testimonialFields = { name: z.string().trim().min(2, "Enter at least 2 characters.").max(160), role: optionalText(160), company: optionalText(160), content: z.string().trim().min(10, "Enter at least 10 characters.").max(4_000), avatarUrl: optionalHttpsUrl, isPublished: z.boolean(), sortOrder: order } satisfies z.ZodRawShape;
export const testimonialCreateSchema = z.object(testimonialFields); export const testimonialUpdateSchema = z.object({ testimonialId: id, ...testimonialFields }); export const testimonialDeleteSchema = z.object({ testimonialId: id, confirmation: z.string().trim().min(1).max(160) });
export type TestimonialInput = z.infer<typeof testimonialCreateSchema>;
function fields(formData: FormData) { return { name: formData.get("name"), role: formData.get("role"), company: formData.get("company"), content: formData.get("content"), avatarUrl: formData.get("avatarUrl"), isPublished: formData.get("isPublished") === "on", sortOrder: formData.get("sortOrder") }; }
export const readTestimonialCreateForm = fields; export function readTestimonialUpdateForm(formData: FormData) { return { testimonialId: formData.get("testimonialId"), ...fields(formData) }; } export function readTestimonialDeleteForm(formData: FormData) { return { testimonialId: formData.get("testimonialId"), confirmation: formData.get("confirmation") }; }
export function toTestimonialData(input: TestimonialInput) { return { name: input.name, role: input.role ?? null, company: input.company ?? null, content: input.content, avatarUrl: input.avatarUrl ?? null, isPublished: input.isPublished, sortOrder: input.sortOrder }; }
