import { beforeEach, describe, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ requireTeamAdmin: vi.fn(), transaction: vi.fn(), create: vi.fn(), findUnique: vi.fn(), update: vi.fn(), remove: vi.fn(), audit: vi.fn(), revalidatePath: vi.fn(), checkAdminMutationLimit: vi.fn() }));
vi.mock("next/cache", () => ({ revalidatePath: mocks.revalidatePath })); vi.mock("@/server/auth/current-user", () => ({ requireTeamAdmin: mocks.requireTeamAdmin })); vi.mock("@/server/db/prisma", () => ({ prisma: { $transaction: mocks.transaction } }));
vi.mock("@/server/security/admin-rate-limit", () => ({ checkAdminMutationLimit: mocks.checkAdminMutationLimit }));
import { createTeamAchievement, deleteTeamAchievement, updateTeamAchievement } from "./team-achievement-actions";
const idle = { status: "idle" as const, message: "" };
function form(id = false) { const data = new FormData(); if (id) data.set("achievementId", "a-1"); data.set("title", "Award"); data.set("description", "Recognition"); data.set("sortOrder", "0"); return data; }
describe("team achievement actions", () => {
  beforeEach(() => { vi.clearAllMocks(); mocks.checkAdminMutationLimit.mockResolvedValue(null); mocks.requireTeamAdmin.mockResolvedValue({ id: "admin" }); mocks.create.mockResolvedValue({ id: "trusted-achievement" }); mocks.findUnique.mockResolvedValue({ id: "trusted-achievement", title: "Award" }); mocks.update.mockResolvedValue({}); mocks.remove.mockResolvedValue({}); mocks.audit.mockResolvedValue({}); mocks.transaction.mockImplementation(async (callback: (tx: unknown) => Promise<unknown>) => callback({ teamAchievement: { create: mocks.create, findUnique: mocks.findUnique, update: mocks.update, delete: mocks.remove }, auditLog: { create: mocks.audit } })); });
  it("requires administrator authorization", async () => { mocks.requireTeamAdmin.mockRejectedValueOnce(new Error("Forbidden")); await expect(createTeamAchievement(idle, form())).rejects.toThrow("Forbidden"); expect(mocks.transaction).not.toHaveBeenCalled(); });
  it("creates and audits allowlisted achievement data", async () => { const data = form(); data.set("memberId", "injected"); expect((await createTeamAchievement(idle, data)).status).toBe("success"); expect(mocks.create).toHaveBeenCalledWith({ data: expect.not.objectContaining({ memberId: expect.anything() }), select: { id: true } }); expect(mocks.audit).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ action: "TEAM_ACHIEVEMENT_CREATED" }) })); });
  it("re-reads the record before updating", async () => { expect((await updateTeamAchievement(idle, form(true))).status).toBe("success"); expect(mocks.findUnique).toHaveBeenCalledWith(expect.objectContaining({ where: { id: "a-1" } })); expect(mocks.update).toHaveBeenCalledWith(expect.objectContaining({ where: { id: "trusted-achievement" } })); });
  it("requires exact current-title deletion confirmation", async () => { const data = new FormData(); data.set("achievementId", "a-1"); data.set("confirmation", "Old title"); const result = await deleteTeamAchievement(idle, data); expect(result.status).toBe("error"); expect(mocks.remove).not.toHaveBeenCalled(); });
  it("deletes and audits after trusted confirmation", async () => { const data = new FormData(); data.set("achievementId", "a-1"); data.set("confirmation", "Award"); expect((await deleteTeamAchievement(idle, data)).status).toBe("success"); expect(mocks.remove).toHaveBeenCalledWith({ where: { id: "trusted-achievement" } }); expect(mocks.audit).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ action: "TEAM_ACHIEVEMENT_DELETED" }) })); });
});
