"use client";

import { useActionState, useState } from "react";
import { createTeamAchievement, deleteTeamAchievement, type TeamAchievementActionState, updateTeamAchievement } from "./team-achievement-actions";

type Achievement = { id: string; title: string; description: string; issuer: string | null; date: string; imageUrl: string | null; url: string | null; sortOrder: number };
const initialState: TeamAchievementActionState = { status: "idle", message: "" };
const input = "min-h-11 w-full rounded-xl border border-white/15 bg-[#111] px-4 text-sm text-white outline-none focus:border-[#ffb800]/70 focus:ring-2 focus:ring-[#ffb800]/20 disabled:opacity-60";
function Message({ state }: { state: TeamAchievementActionState }) { return state.message ? <p aria-live="polite" className={`mt-3 text-sm ${state.status === "success" ? "text-emerald-200" : "text-red-200"}`}>{state.message}</p> : null; }
function Fields({ achievement, pending }: { achievement?: Achievement; pending: boolean }) { return <><label><span className="mb-2 block text-sm font-semibold text-white/70">Title</span><input className={input} defaultValue={achievement?.title ?? ""} disabled={pending} maxLength={200} name="title" required /></label><label><span className="mb-2 block text-sm font-semibold text-white/70">Display order</span><input className={input} defaultValue={achievement?.sortOrder ?? 0} disabled={pending} min={0} name="sortOrder" required type="number" /></label><label className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold text-white/70">Description</span><textarea className={`${input} min-h-28 resize-y py-3`} defaultValue={achievement?.description ?? ""} disabled={pending} maxLength={4000} name="description" required /></label><label><span className="mb-2 block text-sm font-semibold text-white/70">Issuer</span><input className={input} defaultValue={achievement?.issuer ?? ""} disabled={pending} maxLength={200} name="issuer" /></label><label><span className="mb-2 block text-sm font-semibold text-white/70">Date</span><input className={input} defaultValue={achievement?.date ?? ""} disabled={pending} name="date" type="date" /></label><label><span className="mb-2 block text-sm font-semibold text-white/70">Reference URL</span><input className={input} defaultValue={achievement?.url ?? ""} disabled={pending} name="url" type="url" /></label><label><span className="mb-2 block text-sm font-semibold text-white/70">Image URL</span><input className={input} defaultValue={achievement?.imageUrl ?? ""} disabled={pending} name="imageUrl" type="url" /></label></>; }
function Row({ achievement }: { achievement: Achievement }) { const [state, action, pending] = useActionState(updateTeamAchievement, initialState); const [deleteState, deleteAction, deleting] = useActionState(deleteTeamAchievement, initialState); const [confirmation, setConfirmation] = useState(""); return <article className="rounded-3xl border border-white/10 bg-white/[0.025] p-5 sm:p-6"><form action={action} className="grid gap-4 sm:grid-cols-2"><input name="achievementId" type="hidden" value={achievement.id} /><Fields achievement={achievement} pending={pending} /><button className="min-h-11 rounded-full border border-[#ffb800]/35 px-5 text-sm font-semibold text-[#ffc83d] disabled:opacity-50 sm:justify-self-start" disabled={pending} type="submit">{pending ? "Saving…" : "Save achievement"}</button></form><Message state={state} /><form action={deleteAction} className="mt-5 border-t border-white/10 pt-4" onSubmit={(event) => { if (!window.confirm(`Permanently delete ${achievement.title}?`)) event.preventDefault(); }}><input name="achievementId" type="hidden" value={achievement.id} /><label className="block max-w-md"><span className="mb-2 block text-xs text-white/45">Type {achievement.title} to delete</span><input className={input} disabled={deleting} name="confirmation" onChange={(event) => setConfirmation(event.target.value)} value={confirmation} /></label><button className="mt-3 min-h-10 rounded-full border border-red-400/25 px-4 text-xs font-semibold text-red-200 disabled:opacity-35" disabled={deleting || confirmation !== achievement.title} type="submit">{deleting ? "Deleting…" : "Delete achievement"}</button></form><Message state={deleteState} /></article>; }
export function TeamAchievementManager({ achievements }: { achievements: Achievement[] }) { const [state, action, pending] = useActionState(createTeamAchievement, initialState); return <><form action={action} className="mt-8 grid gap-4 rounded-3xl border border-white/10 bg-white/[0.035] p-5 sm:grid-cols-2 sm:p-6"><Fields pending={pending} /><div className="sm:col-span-2"><Message state={state} /></div><button className="min-h-11 rounded-full bg-white px-5 text-sm font-bold text-[#080808] disabled:opacity-50 sm:justify-self-start" disabled={pending} type="submit">{pending ? "Creating…" : "Create achievement"}</button></form>{achievements.length ? <div className="mt-6 grid gap-4">{achievements.map((achievement) => <Row achievement={achievement} key={achievement.id} />)}</div> : <div className="mt-6 rounded-3xl border border-dashed border-white/15 p-8 text-center"><h2 className="font-semibold">No team achievements yet</h2><p className="mt-2 text-sm text-white/45">Create the first achievement above.</p></div>}</>; }
